---
# PostgreSQL

- name: install postgresql packages
  apt: 
    name: '{{ item }}'
    update_cache: 'yes'
    cache_valid_time: 3600
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: enable postgresql service
  become: yes
  service: 
    name: postgresql
    state: started
    enabled: true

- name: ensure database is created
  postgresql_db: name={{dbname}}_production
  become_user: postgres

- name: ensure user has access to database
  postgresql_user: db={{dbname}}_production name={{dbuser}} password={{dbpassword}} priv=ALL
  become_user: postgres

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become_user: postgres

- name: ensure no other user can access the database
  postgresql_privs: db={{dbname}}_production role=PUBLIC type=database priv=ALL state=absent
  become_user: postgres
