---
# MySQL
- name: install mysql
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  become: yes
  with_items:
  - libmysqlclient-dev
  - python-mysqldb
  - mysql-server

# rude, but works, instead using service module
- name: start mysql service
  become: yes
  command: service mysql restart
  args:
    creates: /var/run/mysqld/mysqld.sock

- name: enable mysql service
  become: yes
  service: 
    name: mysql
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  become: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost 
