---
# nginx

- name: ensure nginx is at the latest version
  apt: name=nginx state=latest

- name: add nginx to start on boot
  become: yes
  service:
    name: nginx
    state: started
    enabled: true

- name: upload nginx default site configuration
  template:
    src: 'nginx_default_site.j2'
    dest: '/etc/nginx/sites-available/default'

- name: upload nginx configuration file
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
  notify:
    - restart nginx

# - name: restart nginx
#   service:
#     name: nginx
#     state: restarted

