---
# Capistrano deployment

- name: creates deploy user
  user: 
    name: deploy
    password: '$1$zXNyUjfV$JU.t4NkqTaZfrMFKuhImU0'
    groups: 'www-data,rvm'
    append: yes

- name: installs public key for deploy user
  authorized_key:
    user: deploy
    key: "{{ lookup('file', '{{ssh_public_key}}') }}"

- name: installs private key for deploy user to be used for Capistrano to pull source code from git repo
  copy: 
    src: "{{ ssh_private_key }}" 
    dest: "/home/deploy/.ssh/id_rsa"
    mode: 0600
    owner: deploy


- name: creates webapp directories for deployment
  file: 
    path: '{{ app_dir_root }}/{{ app_name }}/{{ item }}'
    state: directory
    owner: 'deploy'
    group: 'www-data'
    mode: 0775
  with_items:
    - shared/bin
    - shared/config
    - shared/log
    - shared/tmp
    - releases

- name: copies webapp private configs
  become: true
  copy:
    owner: deploy
    group: www-data
    mode: 0640
    src: '{{ src_dir_root }}/{{ app_name }}/config/{{ item.src }}'
    dest: '{{ app_dir_root }}/{{ app_name }}/shared/config/{{ item.dest }}'
  with_items:
    - { src: 'database.yml', dest: 'database.yml' }
    - { src: 'local_env.yml', dest: 'local_env.yml' }
    - { src: 'secrets.yml', dest: 'secrets.yml' }

