---
# Common roles for all hosts

- name: update apt cache and upgrades dist
  apt: 
    upgrade: 'yes'
    update_cache: 'yes'

- name: install the necessary software
  apt: 
    name: '{{ item }}'
    update_cache: 'yes'
    cache_valid_time: 3600
  with_items:
    - '{{ common_packages }}'

# Require for 'pip' ansible module
- name: install the python pip module 
  easy_install:
    name: pip


- include: rvm.yml

- include: capistrano.yml

- include: nodejs.yml

- include: yarn.yml

