---
# Yarn deployment
- name: get yarn gpg key
  get_url: url=https://dl.yarnpkg.com/debian/pubkey.gpg dest=/tmp/yarn_pubkey.gpg mode=0440

- name: add yarn gpg key
  command: apt-key add /tmp/yarn_pubkey.gpg
  become: true

- name: add yarn repo
  shell: 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list'
  become: true
  args:
    executable: /bin/bash

- name: install yarn
  apt: 
    name: 'yarn'
    update_cache: 'yes'
    cache_valid_time: 0
